# Generated by Django 3.1.7 on 2021-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210429_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget_lower',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget_upper',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_text',
            field=models.CharField(default='', max_length=40),
        ),
    ]
