# Generated by Django 3.1.7 on 2021-05-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_profile_image'),
        ('user', '0012_auto_20210501_0828'),
    ]

    operations = [
    ]
